# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: api
output: ../gen/api/api.gen.go
generate:
  gin-server: true
  models: true